/*
 * can_ids.h
 *
 *  Created on: Sep 14, 2025
 *      Author: sara.shabbir-khan
 */

#ifndef INC_CAN_IDS_H_
#define INC_CAN_IDS_H_




#define HPB_CAN_SOURCE_GROUND_SYSTEMS 0x100
#define HPB_CAN_SOURCE_LOWER_TX 0x200
#define HPB_CAN_SOURCE_UPPER_TX 0x300
#define HPB_CAN_SOURCE_LOWER_RX 0x400
#define HPB_CAN_SOURCE_UPPER_RX 0x500


#define HPB_CAN_TYPE_ERR 0x000
#define HPB_CAN_TYPE_SERVO 0x020
#define HPB_CAN_TYPE_THERMOCOUPLE 0x030
#define HPB_CAN_TYPE_PRESSURE 0x040
#define HPB_CAN_TYPE_SERVO_CURRENT 0x050
#define HPB_CAN_TYPE_BATTERY 0x060
#define HPB_CAN_TYPE_STRAIN_GAUGE 0x070
#define HPB_CAN_TYPE_PDU_VOLTAGE 0x080
#define HPB_CAN_TYPE_PDU_CURRENT 0x090
#define HPB_CAN_TYPE_HEARTBEAT 0xA0
#define HPB_CAN_TYPE_SD 0xB0

#define HPB_CAN_INSTANCE_1 0x1
#define HPB_CAN_INSTANCE_2 0x2
#define HPB_CAN_INSTANCE_3 0x3
#define HPB_CAN_INSTANCE_4 0x4
#define HPB_CAN_INSTANCE_5 0x5
#define HPB_CAN_INSTANCE_6 0x6
#define HPB_CAN_INSTANCE_7 0x7

#define HPB_CAN_INSTANCE_PDU 0x1
#define HPB_CAN_INSTANCE_CHARGER 0x2
#define HPB_CAN_INSTANCE_FSCU 0x3
#define HPB_CAN_INSTANCE_GATEWAY 0x4
#define HPB_CAN_INSTANCE_LORACAN 0x4
#define HPB_CAN_INSTANCE_AIRBRAKE_CONTROLLER 0x5
#define HPB_CAN_INSTANCE_AIRBRAKE_BACKUP 0x6


// example: lower stack servo 1:
// (HPB_CAN_SOURCE_LOWER_TX | HPB_CAN_TYPE_SERVO | HPB_CAN_INSTANCE_1)
// Upper FSCU HEARTBEAT (TX)
// (HPB_CAN_SOURCE_UPPER_TX | HPB_CAN_TYPE_HEARTBEAT | HPB_CAN_INSTANCE_FSCU)
// Set lower servo 1
// (HPB_CAN_SOURCE_LOWER_RX | HPB_CAN_TYPE_SERVO | HPB_CAN_INSTANCE_1)





#endif /* INC_CAN_IDS_H_ */
